name: Beast Market Bot

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Market Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MARKET_CHAT_ID: ${{ secrets.MARKET_CHAT_ID }}
        run: python market_bot.py

      - name: Run Portfolio Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          PORTFOLIO_CHAT_ID: ${{ secrets.PORTFOLIO_CHAT_ID }}
        run: python portfolio_bot.py

      - name: Run Action Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ACTION_CHAT_ID: ${{ secrets.ACTION_CHAT_ID }}
          MARKET_CHAT_ID: ${{ secrets.MARKET_CHAT_ID }}
        run: python action_bot.py
